[package]
name = "abizeitungsumfrage"
version = "0.1.0"
edition = "2024"

[dependencies]
actix-web = "4.11.0"
diesel = {version = "2.2.12", features = ["sqlite"]}
dotenv = "0.15.0"
env_logger = "0.11.8"
log = "0.4.27"
serde = {version = "1.0.219", features = ["derive"]}
serde_json = "1.0.142"
