//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "answer")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub sid: i32,
    pub qid: i32,
    #[sea_orm(nullable)]
    pub opt1: Option<i32>,
    #[sea_orm(nullable)]
    pub opt2: Option<i32>,
    #[sea_orm(nullable)]
    pub opt3: Option<i32>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
