//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

pub use super::answer::Entity as Answer;
pub use super::question::Entity as Question;
pub use super::student::Entity as Student;
pub use super::teacher::Entity as Teacher;
