//! `SeaORM` Entity, @generated by sea-orm-codegen 1.1.16

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "question")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    #[sea_orm(column_type = "Text", nullable)]
    pub q: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub opt1: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub opt2: Option<String>,
    #[sea_orm(column_type = "Text", nullable)]
    pub opt3: Option<String>,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
